{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.billyrosty",
    "module": "cyberchat-api",
    "version": "0.1.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cyberchat-api-0.1.0-beta.1.jar",
          "url": "cyberchat-api-0.1.0-beta.1.jar",
          "size": 16364,
          "sha512": "d9adcdce88d4a45b8cb949b4cf0b8c4078d65754903015f5210245e56ea5c0d6b459c17f2daf6c4ea81134c5f7d5c18c443337a1c6795062397dcbe3b568f84c",
          "sha256": "35c83c26da68ead45da08f4436df06f07423122dbef0e2a6eb751a250f5775e3",
          "sha1": "efc348cd539aa758adac547c3f187e020c556a7d",
          "md5": "174a81a7fcfe2f25b9a8686cc2c3b6e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberchat-api-0.1.0-beta.1.jar",
          "url": "cyberchat-api-0.1.0-beta.1.jar",
          "size": 16364,
          "sha512": "d9adcdce88d4a45b8cb949b4cf0b8c4078d65754903015f5210245e56ea5c0d6b459c17f2daf6c4ea81134c5f7d5c18c443337a1c6795062397dcbe3b568f84c",
          "sha256": "35c83c26da68ead45da08f4436df06f07423122dbef0e2a6eb751a250f5775e3",
          "sha1": "efc348cd539aa758adac547c3f187e020c556a7d",
          "md5": "174a81a7fcfe2f25b9a8686cc2c3b6e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberchat-api-0.1.0-beta.1-sources.jar",
          "url": "cyberchat-api-0.1.0-beta.1-sources.jar",
          "size": 14652,
          "sha512": "08cb0603ae063cd8cb90db7b502e4437948c97976759eef81b994b9553ab26cd48b7828e9802a2729a0e7a062660ca9ab2175dc5950d732b083dc60fb99f2a18",
          "sha256": "b10aec4e19dd58c100f2c7ae880bc15da443d082b88c3a85d3755469db257fb0",
          "sha1": "ca491eb8a9138b201ec7a054b4423212d430df16",
          "md5": "0f1482b5e67ef4ad5d9a18e1005f0e83"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberchat-api-0.1.0-beta.1-javadoc.jar",
          "url": "cyberchat-api-0.1.0-beta.1-javadoc.jar",
          "size": 164546,
          "sha512": "e8ceebf619f08e6cc508ad94bf8f5a0d04285ba16876edbc78b983f4b1c8aab590a809fdafa33d4d134230d3240c1f019c830a04d1bccea73bfee4e8fc56b822",
          "sha256": "81c2d59d8cbea48af9128c27ae7e265eabb4bbc3f5dc841d04e09bd89c47f7cb",
          "sha1": "318216965fc17be87c5ef2772d05668d739dec2e",
          "md5": "59fa276c0c5641c46f5c2d4bf6eb0bc9"
        }
      ]
    }
  ]
}
